{
 "title": "tf-ansible-mr-review",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Per Minute (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(sum(increase(tempo_ingester_traces_created_total[1m]))/2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ resource.service.name = \"tf-ansible-mr-review-agent\" && name = \"GET\" || name = \"agent run\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "filters": [
      { "id": "a89463dc", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ resource.service.name = \"tf-ansible-mr-review-agent\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Tool Calls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "filters": [
      { "id": "db6a3e41", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ resource.service.name = \"tf-ansible-mr-review-agent\" && name = \"running tool\" } | select(span.\"gen_ai.tool.name\")",
     "tableType": "spans"
    }
   ]
  }
 ]
}